In [48]:
import pandas as pd

data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

df = pd.DataFrame(data)

df

    Study_Hours  Attendance  Assignments  Marks
0             1          60            2     35
1             2          65            3     40
2             3          70            4     45
3             4          72            5     50
4             5          75            5     58
5             6          80            6     65
6             7          82            7     72
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [49]:
df.to_csv("student_performance.csv", index=False)

print("CSV file created successfully")

CSV file created successfully

In [50]:
df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [51]:
df.tail()

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [52]:
df.shape

(12, 4)

In [53]:
df.columns

Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Study_Hours  12 non-null     int64
 1   Attendance   12 non-null     int64
 2   Assignments  12 non-null     int64
 3   Marks        12 non-null     int64
dtypes: int64(4)
memory usage: 516.0 bytes

In [55]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [56]:
X = df[['Study_Hours', 'Attendance', 'Assignments']]
y = df['Marks']

print("Features (X):")
print(X.head())

print("\nLabel (y):")
print(y.head())

Features (X):
   Study_Hours  Attendance  Assignments
0            1          60            2
1            2          65            3
2            3          70            4
3            4          72            5
4            5          75            5

Label (y):
0    35
1    40
2    45
3    50
4    58
Name: Marks, dtype: int64

In [57]:
workflow_text = """
1. Data Collection:
We collected the student performance dataset which contains Study Hours, Attendance, Assignments and Marks.

2. Data Cleaning:
We checked for missing values and data types. The dataset is clean with no missing values.

3. Feature Selection:
We selected Study_Hours, Attendance and Assignments as input features and Marks as output label.

4. Train-Test Split:
We split the data into training and testing sets to evaluate model performance.

5. Model Training:
We used Linear Regression algorithm to train the model.

6. Testing:
We tested the model using unseen test data.

7. Evaluation:
We evaluated model using MAE and R² score.

8. Prediction:
We used the trained model to predict marks for new student data.
"""

with open("ml_workflow.txt", "w") as f:
    f.write(workflow_text)

print("ml_workflow.txt created successfully")

ml_workflow.txt created successfully

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [59]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (9, 3)
X_test shape: (3, 3)
y_train shape: (9,)
y_test shape: (3,)

In [60]:
X = df[['Study_Hours', 'Attendance', 'Assignments']]
y = df['Marks']

In [61]:
from sklearn.linear_model import LinearRegression

In [62]:
model = LinearRegression()

In [63]:
model.fit(X_train, y_train)

LinearRegression()

In [64]:
print("Coefficients (Slope):", model.coef_)
print("Intercept:", model.intercept_)

Coefficients (Slope): [ 3.45487968  1.34491979 -2.40274064]
Intercept: -48.100601604278054

In [65]:
y_pred = model.predict(X_test)

print("Predicted Marks:")
print(y_pred)

Predicted Marks:
[92.01102941 88.2690508  31.24398396]

In [66]:
new_students = pd.DataFrame({
    "Study_Hours": [5, 8, 12],
    "Attendance": [80, 90, 95],
    "Assignments": [5, 8, 10]
})

new_predictions = model.predict(new_students)

print("New Student Predictions:")
print(new_predictions)

New Student Predictions:
[64.75367647 81.35929144 97.09792781]

In [67]:
y_pred = model.predict(X_test)

print("Predicted Marks (Test Data):")
print(y_pred)

Predicted Marks (Test Data):
[92.01102941 88.2690508  31.24398396]

In [68]:
new_students = pd.DataFrame({
    "Study_Hours": [5, 8, 12],
    "Attendance": [80, 90, 95],
    "Assignments": [5, 8, 10]
})

new_predictions = model.predict(new_students)

print("New Student Predictions:")
print(new_predictions)

New Student Predictions:
[64.75367647 81.35929144 97.09792781]

In [69]:
comparison = pd.DataFrame({
    "Actual Marks": y_test.values,
    "Predicted Marks": y_pred
})

In [70]:
comparison["Difference"] = comparison["Actual Marks"] - comparison["Predicted Marks"]

comparison

   Actual Marks  Predicted Marks  Difference
0            92        92.011029   -0.011029
1            88        88.269051   -0.269051
2            35        31.243984    3.756016

In [71]:
comparison.loc[comparison["Difference"].abs().idxmax()]

Actual Marks       35.000000
Predicted Marks    31.243984
Difference          3.756016
Name: 2, dtype: float64

In [72]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error (MAE):", mae)

Mean Absolute Error (MAE): 1.3453654188948245

In [73]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.9929962957709836

In [74]:
print("Model Performance Summary")
print("MAE:", mae)
print("R² Score:", r2)

Model Performance Summary
MAE: 1.3453654188948245
R² Score: 0.9929962957709836

In [75]:
import plotly.express as px

In [76]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [77]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    title="Attendance vs Marks",
    hover_data=["Assignments"]
)

fig.show()

In [78]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    title="Assignments vs Marks",
    color="Marks"
)

fig.show()

In [79]:
import numpy as np

fig = px.scatter(df, x="Study_Hours", y="Marks", title="Regression Idea")

fig.add_scatter(x=df["Study_Hours"], y=model.predict(X), mode="lines")

fig.show()

In [80]:
future_hours = pd.DataFrame({"Study_Hours": list(range(1,16))})

# default values for other features
future_hours["Attendance"] = 85
future_hours["Assignments"] = 7

future_pred = model.predict(future_hours)

fig = px.line(
    x=future_hours["Study_Hours"],
    y=future_pred,
    title="Predicted Marks Trend"
)

fig.show()

In [81]:
import plotly.express as px

fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [82]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    title="Attendance vs Marks",
    hover_data=["Assignments"]
)

fig.show()

In [83]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    title="Assignments vs Marks",
    color="Marks"
)

fig.show()

In [84]:
fig = px.scatter(df, x="Study_Hours", y="Marks", title="Regression Line")

fig.add_scatter(
    x=df["Study_Hours"],
    y=model.predict(X),
    mode="lines"
)

fig.show()

In [85]:
future = pd.DataFrame({"Study_Hours": list(range(1,16))})
future["Attendance"] = 85
future["Assignments"] = 7

future_pred = model.predict(future)

fig = px.line(
    x=future["Study_Hours"],
    y=future_pred,
    title="Predicted Marks Trend"
)

fig.show()